### PR TITLE
Changes used in the recent skim for data & MC

### PR DESCRIPTION
**Pull request by ArturAkh**
Hi all,

This is now the pull request for the finished skim using the setup of dictchanges branch.

Cheers,

Artur

### CODE REVIEW

**Comment by thomas-mueller** [comment]
Hi Artur,

thanks for the developments. Please give as a bit more details about what you changed and how it affects other/older analyses.

Regards,
Thomas

**Comment by ArturAkh** [comment]
Following changes are done:

- Data Format of Muons, Taus, and Electrons now all derive consistently named dxy and dz from KLepton.
These quantities are filled in corresponding Producers.
- Tau ID related developments (Alex and Stefan)
- restructured checkout script for CMSSW80X
- further developements on the SkimManager

Remark on Travis test:

It fails here because of the Refit Vertex package (used by Claudia). I guess, it's not in the checkout packages scripts used for these tests, am I right? Could someone point me to the way, these tests are build up?

**Comment by thomas-mueller** [comment]
Thanks for the explanation. I will do a test skim tomorrow...

For the tests I think it is more important to care about http://www-ekp.physik.uni-karlsruhe.de/~fcolombo/kappa/test/current/result.html. From the Higgs point-of-view I think the minimum to keep working are the first two lines. Actually there was the agreement, that Olena will take over the scripts and cronjobs from Fabio at some point. Maybe this can be discussed at the DPG, where we should meet each other in person?

**Comment by ArturAkh** [comment]
Hi Thomas, it's fine with me to discuss it at the DPG, but again also for the Kappa Test page I have the impression, that the needed packages are not checked out properly.

**Comment by thomas-mueller** [comment]
At least the error in the first line is exactly the one that Jordy fixed with [this workaround](https://github.com/KappaAnalysis/Kappa/commit/935745c5d8dcdfae2f842971fc9cb141d711b34c) today. So if it was taken serious, it would have been fixed since two months...

**Pull request merged**
