### PR TITLE
Preselection

### PR DESCRIPTION
**Pull request by rfriese**
Cleanup of Higgs config file:
- miniaod vs. aod flags removed (that's why so many lines have been touched)
- drop packedPFCandidates
- only use preselected leptons
- require at least two preselected leptons, otherwise drop this event

Performance on 1000 Events on DY sample:
kappaTuple.root size: 1.9 MB vs. 14 MB
runtime: only 517 events have to be saved, Filling the tree speeds up from 3.2 to 0.7 ms/Event

### CODE REVIEW

**Comment by fcolombo** [comment]
I think that for the preselection is not necessary to use CMSSW EDFilters and create separate electron/muon/taus collections. The corresponding Kappa producers should all inherit from the `KBaseMultiLVProducer` the function `acceptSingle`:
https://github.com/KappaAnalysis/Kappa/blob/CMSSW_7_6_X/Producers/interface/KBaseMultiLVProducer.h#L94-L97
One can then specify at config level the pT and eta cut, as was done here (then it got lost in the various config modifications):
https://github.com/KappaAnalysis/Kappa/blob/master/Skimming/higgsTauTau/kSkimming_cfg.py#L145
The advantage is that this is more compact and independent from the dataformat, while I'm not sure if the EDFilters will work also on non-PAT objects.
Also, I would set the cut a couple of GeVs below the actual analysis thresholds, so that relaxing the cuts can still be done, if needed.

Apart from this, the space reduction is promising and is something that we totally need.

**Comment by rfriese** [comment]
The Kappa pt cuts only allow not selecting the objects but still the rest of the event is written out. The impact there is rather low (probably 10%). The 8.0 cut you are referring to was removed by me because in this setup its obsolete.
I think that it's necessary to at least use EDFilters to not call Kappa for each event at all. On this DY Sample already more than 1/3 of all events do not contain at least 2 leptons with the specified pt and eta cuts. So this does not only save space by avoiding to write out meta information and objects that are always there (MET, PV, ...) but it does as well speed the skim up since a lot of producers do not have to run at all.
We can for sure apply the same cuts on Kappa level with the functionality provided. But then, the same information hast to be encoded twice while at the moment it's only a single point of truth.
Some side information: When using the Filters like now the selectedKappa\* collections basically come for free, since they are needed anyway.

What Non-Pat objects are you referring to? There for sure are also lots of other filters that work on all kinds of objects.

**Comment by rfriese** [comment]
did we come to a conclusion on this? Any other opinions?

**Comment by thomas-mueller** [comment]
Hi Raphael,

The idea to not process every event with Kappa sounds good to me. The only concern I have is that we then cannot use the scripts for determining the number of generated events that we used so far. So if there is a mechanism to identify the number of generated MC events before any cuts, I am fine with this solution.

Cheers,
Thomas

**Comment by rfriese** [comment]
Hi Thomas,

There's even two solutions. The number of generated events is read out from dbs3 since the latest cmssw76 changes.

What has to be adjusted is the determination of the fraction of number of events with positive weights and negative weights. Won't be hard though, the information is stored in histograms in the kappa skims.

Cheers

**Comment by fcolombo** [comment]
I would still suggest to relax the pt cuts on electrons/muons/taus, especialy on the tau side. The exact numbers could be taken from the Run-1 version of the script (was something like 8 GeV, for all the three leptons).

To facilitate performing separate skims where one does not want to apply these selections, might be useful to control this with a boolean option to be given as input (true by default), so that the previous behaviour can be easier reproduced?

**Comment by rcaspart** [comment]
One question that comes to my mind when seeing the changes and effect on the filesize: did you had the chance to check how much of the saving (in filesize) actually comes from dropping the packedPFCandidates and how much is due to having less events in the samples?

**Comment by rfriese** [comment]
@rcaspart on 500 Events SUSY Sync sample I got the following results:
without preselection and with PF Candidates: 500 Events, 7MB
without preselection and without PF Candidates: 500 Events, 1.5 MB
with preselection and with PF Candidates: 350 Events, 5 MB
with preselection, without PF Candidates: 350 Events, 1.1 MB

Yes you're right, the largest gain comes from leaving out the PF Candidates. Still we gain around 30% from the preselection in terms of space and, as well as not to forget in terms of runtime because this events can be skipped directly. Even though this is not a breakthrough the preselection mechanism can easily be adjusted once we have it.

**Pull request merged**
