### PR TITLE
Merging dictchanges branch back into master

### PR DESCRIPTION
**Pull request by ArturAkh**
The developments on the skimming workflow and the electron Id's made by Alex

### CODE REVIEW

**Comment by anehrkor** [comment]
I think this can be merged (after fixing the conflict in datasets.json) now, right? Or are there any objections because of some duplicated files?
I would prefer to have this merged asap and then remove any redundant code later such that we can quickly get up to speed on the analysis level.

**Comment by ArturAkh** [comment]
Hi Alex,

Yes, I'm also for merging asap. If there are any objections, I will prepare the master for the merge (remove or rename the old dataset.json). And then I think every can be automatically merged.

Cheers,

Artur

**Comment by anehrkor** [comment]
Please do not remove/rename the old datasets.json. Github tells you what you need to do in order to fix the merge conflict correctly. Just click on "command line instructions" next to the greyed out "Merge pull request" box ;)

**Comment by ArturAkh** [comment]
This would end up with the same effect. But ok.

**Comment by ArturAkh** [comment]
Ok I merged the two branches via the command line

**Pull request merged**
