### PR TITLE
proposal for rework for crab-submission

### PR DESCRIPTION
**Pull request by rcaspart**
Dear all,

as announced in the Higgs meeting today here is the pull request with suggestions for changes needed for a crab-compatible skimming config.
Please feel free to comment and give suggestions.

Cheers,
Rene

### CODE REVIEW

**Comment by fcolombo** [comment]
Hi,
thanks a lot!
I tested the new kSkimming_run2 script with local test skims (MC/data) and they both run fine provided, of course, that the arguments given via command line are correct.
Trivially, I don't understand how actually submit jobs using crab and what is the usage of the crab-skim.py script (which, by the way, is importing modules from CRABClient/CRABAPI that I don't know where to find...)

**Comment by thomas-mueller** [comment]
Does anything speak against the "standard" argument parser that we are used to from all other scripts?

**Comment by rcaspart** [comment]
Hi Fabio,

Thanks a lot for checking. I forgot to mention that you need to source the file /cvmfs/cms.cern.ch/crab3/crab.sh in order to use crab.
And in order to use the crab script currently you would need to specify the nickname in the python file (as it is done for the Sync-SUSY-sample) and then run python crab-skim.py submit

**Comment by fcolombo** [comment]
Hi Rene,
thanks, now the whole mechanism is much clearer. I still was not able to submit a test skim on the grid because of some CRAB errors ("File is bigger then allowed limit of 104857600B", apparently) and I would like to understand this and do some more tests, from the week after the next one.

However, after all this is just a pull request and we can improve the whole thing once is merged.
As far as I see, this pull request becomes completely non-controversial, if we rename the CRAB-modified config in a different way and leave kSkimming_run2_cfg as before. Am I right on this?
In this way we can do our CRAB tests and keep using the old config for skimming with GC (and this will also not break the Kappa test suite, for the moment). Of course this will bring the risk of code duplication and possible mismatches between the configs, but it should not be difficult to behave ourselves.
So I'm fine in accepting the pull request, with the caveat above. Just my 2 cents.

**Comment by JoramBerger** [comment]
@thomas-mueller Yes, I think CMSSW (cmsRun) just does not pass the arguments and the argument parser won't get them. We all would opt for that if it was possible.
@rcaspart Thanks a lot, I think it is a good thing and quite non-controversial. It looks to me like the GC-way can be continued and CRAB comes in addition, that's good. I have some comments though:
- There should be default arguments similar to before such that the test knows what to do - including the lookup of ekp and naf paths (the alternative would be to implement arguments in the test which is probably a bit more work)
- You can run the tests yourself as documented
- When the tests run, it should be easier to check whether the output is identical for CRAB and GC (that should be checked)
- I would suggest to make a new pull request to development as this can be used independently of the dict-changes (if that is problematic, it is not necessary, though)

**Comment by rcaspart** [comment]
@thomas-mueller As Joram said the "standard" argument parser does not work for the cmsRun configurations. At least in a short test I was not able to get both to work together.
@fcolombo As I recall the problem is that the CMSSW work-area has a too large size. In the checkout script I tried to take care of this by checking out Raphaels repository as a shallow on (adding --depth 1). This reduces the size by quite some fraction and the area is then small enough to be submitted.
Regarding the separate config: I am fine with having a separate configuration during "development". I can include that in a pull request for the development branch.
@JoramBerger I think it should be easy to implement the changes to have it running like previously when not provided with any arguments. I will have a look into this tomorrow. Once this is done I can then also provide it as pull request to the development branch.
As for comparing the output: I have skimmed our Higgs sync-samples using both gc and crab with the new config and produced the corresponding ntuples and they are identical (see http://www-ekp.physik.uni-karlsruhe.de/~rcaspart/plots_archive/2015_08_25/). I will run one more check for comparing new vs. old config.
Do you have any other suggestions on how to check that the skims are identical?

**Comment by thomas-mueller** [comment]
Dear all,

what is the status of this development? Is somebody pushing it? It seems, that the need for a (well-tested and usable) crab setup constantly grows.

Cheers,
Thomas

**Comment by JoramBerger** [comment]
It seems nobody, since René is not available at the moment. Can anyone take over?

**Comment by rfriese** [comment]
Hi,

currently having a look. Let you know if it works out.

Cheers,

Raphael

On 16.09.2015 16:16, Joram Berger wrote:

> It seems nobody, since René is not available at the moment. Can anyone 
> take over?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/KappaAnalysis/Kappa/pull/1#issuecomment-140754373.

## 

Raphael Friese

Karlsruhe Institute of Technology (KIT)
Kaiserstraße 12
Building 30.23 / R 8-22
76131 Karlsruhe, Germany
Phone: +49 721 608-47243

CERN
Building 32-4 B06
Phone: +41 22 76-78267

Email: Raphael.Friese@cern.ch

**Comment by rcaspart** [comment]
This improvement was incorporated in the dictchanges branch with #5. Closing

**Pull request closed without merging**
