### PR TITLE
Merge to the master: Kappa_2_2_0

### PR DESCRIPTION
**Pull request by rfriese**
Dear all,

since our PDF guys succeeded today I think we should no longer wait to merge the 76X branch to the master. The next step will then be to branch out a CMSSW_8_0_X branch where some updates have to be made. Also, dictionary changes will be necessary (e.g. from the theoryunc branch).

Does everyone agree with the merge? If yes, I'll merge next week.

Cheers

### CODE REVIEW

**Comment by pistone87** [comment]
Dear all, 

when running the checkout recipe for the Skimming, i got this message:

``` bash
command: git cms-merge-topic -u KappaAnalysis:Kappa_CMSSW_763
No release tags specified, using default CMSSW_7_6_3.
Fetching origin
From https://github.com/cms-sw/cmssw
 * branch            HEAD       -> FETCH_HEAD
tee: standard output: Broken pipe
tee: write error
```

Any idea why is that?

**Comment by rcaspart** [comment]
Hi Claudia,

as I recall this is within the cms-git-tools and not problematic at all. Do you experience any problems (apart from just this message)?

Cheers,
Rene

**Comment by pistone87** [comment]
Hi Rene,

No, no problems: the checkout recipe worked out well.
I was just wondering about those lines, if they were relevant.

Thanks.

Cheers,
Claudia

**Comment by thomas-mueller** [comment]
My impression was, that just the information about the merged branch is missing. I thought, that [this line](https://github.com/KappaAnalysis/Kappa/blob/master/Skimming/scripts/checkoutCmssw76xPackagesForSkimming.py#L61) should maybe be

``` bash
git cms-merge-topic -u KappaAnalysis:Kappa_master
```

but this does not seem to work, as Claudia says.

Btw. also [recipe in the wiki](https://github.com/cms-analysis/HiggsAnalysis-KITHiggsToTauTau/wiki/Skimming#cmssw_7_6_3) needs to be adjusted, when branches change, which Claudia already did.

**Comment by rfriese** [comment]
the cms-merge-topic has nothing to do with the Kappa branch. This command does a merge of cmssw with the version forked to the KappaAnalysis github account. 

I just did a fresh checkout of CMSSW_7_6_3 and the cms-merge-topic command without any problems. The error message says that it's not able to write some output, at the moment I can't see the connection to this merge?

**Pull request merged**
